const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '../src/environments');

if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

const content = `// This file was generated by scripts/set-env.js
export const environment = {
  production: true,
  supabase: {
    url: '${process.env.SUPABASE_URL || ""}',
    anonKey: '${process.env.SUPABASE_KEY || ""}'
  }
};
`;

fs.writeFileSync(path.join(dir, 'environment.ts'), content);
console.log('Environment file generated successfully at: ' + path.join(dir, 'environment.ts'));
